on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@master

      - name: Install system dependencies
        run: |
          brew cask install xquartz
          brew install pkg-config cairo
          brew install v8

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Configure Git user
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@master

      - name: Build site
        run: |
          sudo apt-get install asymptote
          R -e 'install.packages(c("bookdown", "knitr", "xfun", "rmarkdown", "tinytex"))'
          R -e 'tinytex::tlmgr_install(c("pgf", "preview", "xcolor", "grfext"))'
          make gitbook

      - name: Deploy to Netlify
        if: github.ref != 'refs/heads/master'
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './_book'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
